spring:
  application: name:movie-ticket
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Hikari
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngoanhtien902@gmail.com
    password: Anhtien123.
    transport:
      protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

security:
  jwt:
    secret: Y2JkN2M4NjU3NTM4Y2ZiNDEyMjU5NjM1ZGVhMDIwOGFiMzZiYjY0MTJmMDVlZTY3ZTQyMzZjMTA4YWIxODk3YzI4MTkxNTkzZjFmYmQ5ZGM5MTA1NmVmZjAyODExZTQxMGRlMWI1M2U5MDEzNDY1ZDJhMmZiODhmMDI0MWYyNWQ=
    # Token is valid 24 hours
    token-validity-in-seconds: 86400
    token-refresh-in-seconds: 2629743

resetPasswordBody: "Kính gửi {0}\\n\\nBạn đã yếu cầu đặt lại mật khẩu cho tài khoản của mình trong trống tính năng \"Quên mật khẩu\".\\nChúng tôi xin xác nhận rằng mật khẩu đã được thay đổi có thể có cho tài: {1}\\nNếu bạn không thực hiện hiện yêu cầu yêu này, vui lòng liên hệ với chúng tôi ngay lập tức thời và đảm bảo an toàn tài khoản của bạn.\\n\\nCảm ơn bạn đã sử dụng dịch vụ của chúng tôi."
resetPasswordSubject: "Thông báo thay đổi password"
cloudinary:
  cloud_name: a
  api_key: 7
  api_secret: a-a
  secure: true
